global_vars:
  - name: prenom
    type: echo
    params:
      echo: "Cyril"
  - name: nom
    type: echo
    params:
      echo: "Cyril"
matches:
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d/%m/%Y"
          
