global_vars:
  - name: prenom
    type: echo
    params:
      echo: "Cyril"
  - name: nom
    type: echo
    params:
      echo: "Humbert"
matches:
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d/%m/%Y"

  - trigger: ":me"
    replace: "{{nom}} {{prenom}}"
  - trigger: ":CB"
    replace: "Cy-Bert"
  - trigger: ":mail"
    replace: "cyril.humbert.70@gmail.com"
    # cyril.humbert.70@gmail.com
